"use client";

import React, { useState } from "react";
import { useCarbonStore } from "@/store/useCarbonStore";
import { jsPDF } from "jspdf";
import { Search, FileDown, BookOpen, ExternalLink, Leaf, Award, Download, Share2 } from "lucide-react";

interface Article {
  id: string;
  title: string;
  category: "basics" | "energy" | "transit" | "waste" | "diet";
  excerpt: string;
  readTime: string;
  content: string;
}

const articlesCatalog: Article[] = [
  {
    id: "a1",
    title: "Understanding Carbon Footprint Basics",
    category: "basics",
    excerpt: "What exactly is CO2e, and how does personal lifestyle output compare to global grid metrics?",
    readTime: "4 min read",
    content: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2°C rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.",
  },
  {
    id: "a2",
    title: "Community Solar & Green Grid Tariffs",
    category: "energy",
    excerpt: "How to swap your home electricity utility to 100% renewable wind and solar without rooftop installations.",
    readTime: "5 min read",
    content: "If you cannot install rooftop solar panels (e.g., if you rent or live in an apartment), you can still transition your household power to clean energy. Many utilities allow selecting a green power provider or joining a local community solar farm. This directly offsets your carbon impact from domestic electricity to zero.",
  },
  {
    id: "a3",
    title: "Decarbonizing Commutes: EV vs. Transit",
    category: "transit",
    excerpt: "A deep dive comparing the lifetime emissions of electric vehicle battery production vs. diesel/electric rail.",
    readTime: "6 min read",
    content: "Electric vehicles (EVs) have higher manufacturing emissions due to battery cells, but quickly offset this within 6-18 months of driving. However, public rail transit remains the gold standard. High-occupancy electric buses and trains release 85% less CO2 per passenger mile compared to private vehicle trips.",
  },
  {
    id: "a4",
    title: "Anaerobic Decomposition & Landfill Methane",
    category: "waste",
    excerpt: "Why food waste discarded in plastic bags forms landfill methane, and how composting prevents it.",
    readTime: "5 min read",
    content: "Organic waste buried in modern landfills decomposes anaerobically (without oxygen). This process generates methane, a greenhouse gas 28x more potent than carbon dioxide at trapping atmospheric heat. Composting exposes scraps to oxygen, causing aerobic decomposition, which releases natural biogenic CO2 instead.",
  },
  {
    id: "a5",
    title: "The Carbon Impact of Animal Agriculture",
    category: "diet",
    excerpt: "Why beef production requires 20x more land and releases up to 10x more emissions than poultry.",
    readTime: "7 min read",
    content: "Cattle are ruminant animals, meaning their digestive systems produce methane. Additionally, clearing forests for pastureland releases massive amounts of carbon stored in soil and trees. Shifting to plant-based meals, even partially, represents the highest single lifestyle reduction you can achieve.",
  },
];

export const EducationHub: React.FC = () => {
  const { results, inputs, roadmap } = useCarbonStore();
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState<string>("all");
  const [copied, setCopied] = useState(false);

  // Filter articles
  const filteredArticles = articlesCatalog.filter((art) => {
    const matchesSearch =
      art.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      art.excerpt.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = activeCategory === "all" || art.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  // Export PDF Report Utility
  const handleExportPDF = () => {
    try {
      if (!results) return;

      const doc = new jsPDF();
      const annualTons = (results.annualEmissions / 1000).toFixed(1);
      const monthlyTons = (results.monthlyEmissions / 1000).toFixed(2);
      const potentialTons = (results.reductionPotential / 1000).toFixed(1);

      // Styling
      doc.setFillColor(11, 19, 38); // Deep Space Blue
      doc.rect(0, 0, 210, 297, "F");

      // Title
      doc.setTextColor(78, 222, 163); // Emerald Green
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("EcoSphere AI - CarbonLens Report", 20, 30);

      // Tagline
      doc.setTextColor(187, 202, 191);
      doc.setFontSize(10);
      doc.setFont("helvetica", "italic");
      doc.text("See Your Impact. Shape a Greener Future.", 20, 36);

      // Separator line
      doc.setDrawColor(40, 50, 70);
      doc.line(20, 42, 190, 42);

      // Section: Metrics
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Sustainability Metrics Index", 20, 52);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(218, 226, 253);
      doc.text(`* Sustainability Index Score: ${results.sustainabilityScore} / 100`, 20, 62);
      doc.text(`* Total Annual Carbon Footprint: ${annualTons} Metric Tons CO2e`, 20, 68);
      doc.text(`* Average Monthly Carbon Footprint: ${monthlyTons} Metric Tons CO2e`, 20, 74);
      doc.text(`* Planned Carbon Reduction Potential: ${potentialTons} Metric Tons / year`, 20, 80);

      // Section: Category Breakdown
      doc.setFont("helvetica", "bold");
      doc.setTextColor(78, 222, 163);
      doc.text("Category Emissions Breakdown (kg CO2e / year)", 20, 95);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(218, 226, 253);
      doc.text(`* Transportation: ${results.breakdown.transportation} kg`, 20, 105);
      doc.text(`* Grid Energy: ${results.breakdown.energy} kg`, 20, 111);
      doc.text(`* Diet & Food: ${results.breakdown.food} kg`, 20, 117);
      doc.text(`* Consumer Shopping: ${results.breakdown.shopping} kg`, 20, 123);
      doc.text(`* Waste & Landfills: ${results.breakdown.waste} kg`, 20, 129);

      // Section: Hotspots
      doc.setFont("helvetica", "bold");
      doc.setTextColor(78, 222, 163);
      doc.text("Identified Hotspots & AI Advice", 20, 144);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(218, 226, 253);
      results.hotspots.forEach((hs, idx) => {
        const yPos = 154 + idx * 16;
        if (yPos < 260) {
          doc.setFont("helvetica", "bold");
          doc.text(`[${hs.impact}] ${hs.title}`, 20, yPos);
          doc.setFont("helvetica", "normal");
          const splitText = doc.splitTextToSize(hs.description, 170);
          doc.text(splitText, 20, yPos + 6);
        }
      });

      // Page 2: Roadmap Tasks
      doc.addPage();
      doc.setFillColor(11, 19, 38);
      doc.rect(0, 0, 210, 297, "F");

      doc.setTextColor(78, 222, 163);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text("Active Decarbonization Roadmap", 20, 30);
      doc.line(20, 36, 190, 36);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(218, 226, 253);

      const activeTasks = roadmap.filter((r) => !r.completed);
      if (activeTasks.length === 0) {
        doc.text("All planned reduction steps completed! Keep up the outstanding work.", 20, 48);
      } else {
        activeTasks.forEach((task, idx) => {
          const yPos = 48 + idx * 24;
          if (yPos < 270) {
            doc.setFont("helvetica", "bold");
            doc.text(`${idx + 1}. ${task.title} (${task.timeframe})`, 20, yPos);
            doc.setFont("helvetica", "normal");
            doc.text(`Action: ${task.description}`, 20, yPos + 6);
            doc.setTextColor(78, 222, 163);
            doc.text(`Savings: -${task.co2Reduction} kg CO2/year`, 20, yPos + 12);
            doc.setTextColor(218, 226, 253);
          }
        });
      }

      doc.save("EcoSphereAI_CarbonLens_Report.pdf");
    } catch (err: any) {
      console.error("PDF generation failed:", err);
      alert("Failed to export PDF: " + err.message);
    }
  };

  // Draw and download scorecard image
  const handleDownloadCard = () => {
    if (!results) return;
    try {
      const canvas = document.createElement("canvas");
      canvas.width = 600;
      canvas.height = 360;
      const ctx = canvas.getContext("2d");
      if (!ctx) throw new Error("Could not get 2D context");

      // Background Gradient
      const gradient = ctx.createLinearGradient(0, 0, 600, 360);
      gradient.addColorStop(0, "#0b1326");
      gradient.addColorStop(1, "#15243f");
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, 600, 360);

      // Outer border
      ctx.strokeStyle = "#4edea3";
      ctx.lineWidth = 4;
      ctx.strokeRect(10, 10, 580, 340);

      // Title & Branding
      ctx.fillStyle = "#4edea3";
      ctx.font = "bold 20px Helvetica, Arial, sans-serif";
      ctx.fillText("ECOSPHERE AI - CARBONLENS", 30, 45);

      ctx.fillStyle = "#bbcaa7";
      ctx.font = "italic 11px Helvetica, Arial, sans-serif";
      ctx.fillText("See Your Impact. Shape a Greener Future.", 30, 62);

      // Divider line
      ctx.strokeStyle = "rgba(255, 255, 255, 0.1)";
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(30, 80);
      ctx.lineTo(570, 80);
      ctx.stroke();

      // Left Column: Sustainability Score
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 12px Helvetica, Arial, sans-serif";
      ctx.fillText("SUSTAINABILITY INDEX", 30, 115);

      // Draw large score
      ctx.fillStyle = "#4edea3";
      ctx.font = "bold 44px Helvetica, Arial, sans-serif";
      ctx.fillText(`${results.sustainabilityScore}`, 30, 165);

      ctx.fillStyle = "rgba(255, 255, 255, 0.5)";
      ctx.font = "normal 14px Helvetica, Arial, sans-serif";
      ctx.fillText("/ 100", 110, 165);

      // Score rating text
      let scoreRating = "Needs Action";
      let ratingColor = "#ff6b6b";
      if (results.sustainabilityScore >= 75) {
        scoreRating = "Eco Hero";
        ratingColor = "#4edea3";
      } else if (results.sustainabilityScore >= 50) {
        scoreRating = "Eco Explorer";
        ratingColor = "#a3e635";
      }
      ctx.fillStyle = ratingColor;
      ctx.font = "bold 13px Helvetica, Arial, sans-serif";
      ctx.fillText(`Eco-Status: ${scoreRating}`, 30, 195);

      // Progress bar below rating
      ctx.fillStyle = "rgba(255, 255, 255, 0.1)";
      ctx.fillRect(30, 215, 220, 10);
      ctx.fillStyle = "#4edea3";
      ctx.fillRect(30, 215, 2.2 * results.sustainabilityScore, 10);

      // Right Column: Emissions details
      const rightX = 320;
      
      // Annual Emissions
      ctx.fillStyle = "rgba(255, 255, 255, 0.6)";
      ctx.font = "bold 10px Helvetica, Arial, sans-serif";
      ctx.fillText("ANNUAL CARBON FOOTPRINT", rightX, 115);
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 18px Helvetica, Arial, sans-serif";
      ctx.fillText(`${(results.annualEmissions / 1000).toFixed(1)} Tons CO₂e`, rightX, 138);

      // Monthly Emissions
      ctx.fillStyle = "rgba(255, 255, 255, 0.6)";
      ctx.font = "bold 10px Helvetica, Arial, sans-serif";
      ctx.fillText("MONTHLY AVERAGE", rightX, 175);
      ctx.fillStyle = "#dae2fd";
      ctx.font = "bold 18px Helvetica, Arial, sans-serif";
      ctx.fillText(`${(results.monthlyEmissions / 1000).toFixed(2)} Tons CO₂e`, rightX, 198);

      // Reduction Potential
      ctx.fillStyle = "rgba(255, 255, 255, 0.6)";
      ctx.font = "bold 10px Helvetica, Arial, sans-serif";
      ctx.fillText("ANNUAL SAVINGS POTENTIAL", rightX, 235);
      ctx.fillStyle = "#4edea3";
      ctx.font = "bold 18px Helvetica, Arial, sans-serif";
      ctx.fillText(`${(results.reductionPotential / 1000).toFixed(1)} Tons CO₂`, rightX, 258);

      // Lower Divider
      ctx.strokeStyle = "rgba(255, 255, 255, 0.05)";
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(30, 290);
      ctx.lineTo(570, 290);
      ctx.stroke();

      // Verification Footnote
      ctx.fillStyle = "rgba(255, 255, 255, 0.35)";
      ctx.font = "normal 10px Helvetica, Arial, sans-serif";
      ctx.fillText("Verified by EcoSphere AI Climate Platform", 30, 325);

      // Convert to DataURL and trigger download
      const dataUrl = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = `EcoSphere_CarbonLens_Scorecard_${results.sustainabilityScore}.png`;
      link.click();
    } catch (err: any) {
      console.error("Canvas drawing failed:", err);
      alert("Failed to download card: " + err.message);
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-6 py-8 flex flex-col gap-10 text-left">
      
      {/* Header and Report Export panel */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
        <div className="lg:col-span-7 flex flex-col gap-4">
          <span className="font-label-caps text-label-caps text-primary uppercase">Climate Action Hub</span>
          <h2 className="font-headline-lg text-headline-lg">Education & Reports</h2>
          <p className="text-on-surface-variant text-sm leading-relaxed max-w-xl">
            Learn the science driving decarbonization indices, download your calculated audits, and share your scorecards with colleagues and peers.
          </p>
        </div>

        {/* PDF Export Panel */}
        <div className="lg:col-span-5 glass-card rounded-2xl p-6 flex flex-col gap-4 border border-primary/20">
          <div className="flex items-center gap-2 border-b border-white/5 pb-3">
            <Award className="text-primary h-5 w-5 animate-pulse" />
            <h3 className="font-headline-md text-headline-md text-sm font-bold">Share Your Achievements</h3>
          </div>
          
          {results ? (
            <div className="flex flex-col gap-3">
              <div className="flex justify-between items-center bg-white/[0.02] p-3 rounded-xl border border-white/5">
                <span className="text-xs text-on-surface-variant">Sustainability Index</span>
                <span className="text-lg font-bold text-primary font-data-point">{results.sustainabilityScore} / 100</span>
              </div>
              <div className="flex gap-3">
                <button
                  onClick={handleExportPDF}
                  className="flex-1 px-4 py-3 bg-primary text-on-primary font-bold rounded-xl text-xs flex items-center justify-center gap-2 hover:scale-105 transition-all cursor-pointer shadow-md"
                >
                  <FileDown className="h-4 w-4" /> Download PDF Report
                </button>
                <button
                  onClick={handleDownloadCard}
                  className="px-4 py-3 glass-card text-on-surface font-bold rounded-xl text-xs flex items-center justify-center gap-2 hover:bg-white/10 transition-all cursor-pointer"
                >
                  <Share2 className="h-4 w-4" /> Share Card (PNG)
                </button>
              </div>
            </div>
          ) : (
            <div className="text-center py-4">
              <p className="text-xs text-on-surface-variant">Please complete the assessment wizard to unlock your reporting package.</p>
            </div>
          )}
        </div>
      </div>

      {/* Directory Section */}
      <div className="flex flex-col gap-6">
        {/* Search and filter bars */}
        <div className="flex flex-col sm:flex-row justify-between items-stretch sm:items-center gap-4 border-t border-white/5 pt-8">
          {/* Categories select pills */}
          <div className="flex flex-wrap gap-2">
            {[
              { key: "all", label: "All Topics" },
              { key: "basics", label: "Basics" },
              { key: "energy", label: "Clean Grid" },
              { key: "transit", label: "Transit" },
              { key: "waste", label: "Zero Waste" },
              { key: "diet", label: "Eco Diet" },
            ].map((cat) => (
              <button
                key={cat.key}
                onClick={() => setActiveCategory(cat.key)}
                className={`px-4 py-2 rounded-full border text-xs font-semibold cursor-pointer transition-all ${
                  activeCategory === cat.key
                    ? "bg-primary/20 border-primary text-primary"
                    : "bg-surface-container border-white/5 text-on-surface hover:bg-white/5"
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>

          {/* Search box */}
          <div className="relative max-w-xs w-full">
            <Search className="absolute left-3 top-3 h-4 w-4 text-on-surface-variant" />
            <input
              type="text"
              placeholder="Search directory..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-surface-container border border-white/10 focus:border-primary focus:ring-1 focus:ring-primary rounded-xl pl-9 pr-4 py-2.5 text-xs text-on-surface focus:outline-none placeholder:text-on-surface-variant"
            />
          </div>
        </div>

        {/* Directory Listing Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredArticles.map((art) => (
            <div key={art.id} className="glass-card rounded-2xl p-6 flex flex-col justify-between hover:bg-white/5 transition-all h-[240px]">
              <div className="flex flex-col gap-3">
                <div className="flex justify-between items-center text-[10px] font-label-caps text-on-surface-variant uppercase">
                  <span className="text-primary font-bold">{art.category}</span>
                  <span>{art.readTime}</span>
                </div>
                <h4 className="font-bold text-sm text-on-surface font-headline-md leading-snug">{art.title}</h4>
                <p className="text-xs text-on-surface-variant leading-relaxed line-clamp-3">{art.excerpt}</p>
              </div>
              
              {/* Modal or Read Article Link */}
              <div className="border-t border-white/5 pt-3 mt-4 flex items-center justify-between">
                <span className="text-[10px] font-label-caps text-on-surface-variant">CarbonLens Learning</span>
                <button
                  onClick={() => alert(`Article Content:\n\n${art.content}`)}
                  className="text-xs font-bold text-primary hover:underline flex items-center gap-1.5 cursor-pointer font-label-caps uppercase"
                >
                  Read Guides <ExternalLink className="h-3 w-3" />
                </button>
              </div>
            </div>
          ))}

          {filteredArticles.length === 0 && (
            <div className="col-span-full py-12 text-center text-on-surface-variant text-sm">
              No guides match your active category and search filter.
            </div>
          )}
        </div>
      </div>

    </div>
  );
};
export default EducationHub;
